name: testaaaa
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  sqflite: ^2.4.2
  path: ^1.9.1
  sqflite_common_ffi: ^2.3.5
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.2 # 시간대 지원용

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
